@startuml

title __PROJECT-STARTER's Class Diagram__\n

  namespace model.data {
    abstract class model.data.Datum {
    }
  }
  

  namespace model.data {
    class model.data.DatumLink {
    }
  }
  

  namespace model.data {
    class model.data.DatumQueryService {
    }
  }
  

  namespace model.data {
    class model.data.Qualifier {
    }
  }
  

  namespace model.data {
    class model.data.Reference {
    }
  }
  

  namespace model.data {
    class model.data.ScopedSearch {
    }
  }
  

  namespace model.data {
    class model.data.Statement {
    }
  }
  

  namespace model.data {
    abstract class model.data.Value {
    }
  }
  

  namespace model.data {
    namespace additional {
      abstract class model.data.additional.AbstractAdditional {
      }
    }
  }
  

  namespace model.data {
    namespace additional {
      class model.data.additional.CommonsMedia {
      }
    }
  }
  

  namespace model.data {
    namespace additional {
      class model.data.additional.ExternalIdentifier {
      }
    }
  }
  

  namespace model.data {
    namespace additional {
      class model.data.additional.GeographicShape {
      }
    }
  }
  

  namespace model.data {
    namespace additional {
      class model.data.additional.GlobeCoordinate {
      }
    }
  }
  

  namespace model.data {
    namespace additional {
      class model.data.additional.LiteralString {
      }
    }
  }
  

  namespace model.data {
    namespace additional {
      class model.data.additional.MathematicalExpression {
      }
    }
  }
  

  namespace model.data {
    namespace additional {
      class model.data.additional.MonolingualText {
      }
    }
  }
  

  namespace model.data {
    namespace additional {
      class model.data.additional.MusicalNotation {
      }
    }
  }
  

  namespace model.data {
    namespace additional {
      class model.data.additional.Quantity {
      }
    }
  }
  

  namespace model.data {
    namespace additional {
      class model.data.additional.TabularData {
      }
    }
  }
  

  namespace model.data {
    namespace additional {
      class model.data.additional.Time {
      }
    }
  }
  

  namespace model.data {
    namespace additional {
      class model.data.additional.URL {
      }
    }
  }
  

  namespace model.data {
    namespace pages {
      class model.data.pages.Item {
      }
    }
  }
  

  namespace model.data {
    namespace pages {
      class model.data.pages.Property {
      }
    }
  }
  

  namespace model.data {
    namespace pages {
      namespace language {
        class model.data.pages.language.Form {
        }
      }
    }
  }
  

  namespace model.data {
    namespace pages {
      namespace language {
        class model.data.pages.language.Lexeme {
        }
      }
    }
  }
  

  namespace model.data {
    namespace pages {
      namespace language {
        class model.data.pages.language.Sense {
        }
      }
    }
  }
  

  namespace model.data {
    namespace source {
      interface model.data.source.Collector {
      }
    }
  }
  

  namespace model.data {
    namespace source {
      class model.data.source.LocalCollector {
      }
    }
  }
  

  namespace model.data {
    namespace source {
      class model.data.source.LocalRepository {
      }
    }
  }
  

  namespace model.data {
    namespace source {
      class model.data.source.WebCollector {
      }
    }
  }
  

  namespace model.data {
    namespace source {
      namespace template {
        class model.data.source.template.Alias {
        }
      }
    }
  }
  

  namespace model.data {
    namespace source {
      namespace template {
        class model.data.source.template.Claim {
        }
      }
    }
  }
  

  namespace model.data {
    namespace source {
      namespace template {
        class model.data.source.template.DataValue {
        }
      }
    }
  }
  

  namespace model.data {
    namespace source {
      namespace template {
        class model.data.source.template.Description {
        }
      }
    }
  }
  

  namespace model.data {
    namespace source {
      namespace template {
        class model.data.source.template.Entities {
        }
      }
    }
  }
  

  namespace model.data {
    namespace source {
      namespace template {
        class model.data.source.template.Entity {
        }
      }
    }
  }
  

  namespace model.data {
    namespace source {
      namespace template {
        class model.data.source.template.Label {
        }
      }
    }
  }
  

  namespace model.data {
    namespace source {
      namespace template {
        class model.data.source.template.Qualifier {
        }
      }
    }
  }
  

  namespace model.data {
    namespace source {
      namespace template {
        class model.data.source.template.Reference {
        }
      }
    }
  }
  

  namespace model.data {
    namespace source {
      namespace template {
        class model.data.source.template.SiteLink {
        }
      }
    }
  }
  

  namespace model.data {
    namespace source {
      namespace template {
        class model.data.source.template.Snak {
        }
      }
    }
  }
  

  namespace model.prefrences {
    class model.prefrences.LayoutProfile {
    }
  }
  

  namespace model.prefrences {
    class model.prefrences.LayoutProfileManager {
    }
  }
  

  namespace model.prefrences {
    class model.prefrences.PreferenceManager {
    }
  }
  

  namespace model.prefrences {
    class model.prefrences.SerialIOController {
    }
  }
  

  namespace model.prefrences {
    interface model.prefrences.UserPreference {
    }
  }
  

  namespace model.prefrences {
    class model.prefrences.UserProfile {
    }
  }
  

  namespace model.util {
    class model.util.StringBuilderUtil {
    }
  }
  

  namespace ui {
    class ui.CLInterface {
    }
  }
  

  namespace ui {
    class ui.cli.ItemView {
    }
  }
  

  namespace ui {
    class ui.cli.ItemViewController {
    }
  }
  

  namespace ui {
    class ui.cli.LayoutManager {
    }
  }
  

  namespace ui {
    class ui.cli.MenuBar {
    }
  }
  

  namespace ui {
    interface ui.cli.MenuBarItem {
    }
  }
  

  namespace ui {
    class ui.cli.SearchBar {
    }
  }
  

  namespace ui {
    class ui.cli.StatementList {
    }
  }
  

  model.data.Datum -up-|> model.data.Value
  model.data.Datum o-- ui.cli.StatementList : statements
  model.data.DatumLink -up-|> model.data.Value
  model.data.DatumLink o-- model.data.Statement : property
  model.data.DatumLink o-- ui.cli.StatementList : statementList
  model.data.DatumLink o-- model.data.Value : value
  model.data.DatumQueryService o-- model.data.source.Collector : collector
  model.data.Qualifier -up-|> model.data.Value
  model.data.Qualifier o-- model.data.pages.Property : property
  model.data.Qualifier o-- model.data.Value : value
  model.data.Reference -up-|> model.data.Value
  model.data.Reference o-- model.data.pages.Property : property
  model.data.Reference o-- model.data.Value : value
  model.data.ScopedSearch o-- ui.cli.ItemViewController : controller
  model.data.ScopedSearch o-- model.data.Value : item
  model.data.ScopedSearch o-- model.data.DatumQueryService : queryService
  model.data.Statement -up-|> model.data.Value
  model.data.Statement o-- model.data.Datum : about
  model.data.Statement o-- ui.cli.StatementList : statements
  model.data.Value o-- model.data.DatumQueryService : queryService
  model.data.Value o-- ui.cli.ItemView : view
  model.data.additional.AbstractAdditional -up-|> model.data.Value
  model.data.additional.CommonsMedia -up-|> model.data.additional.AbstractAdditional
  model.data.additional.ExternalIdentifier -up-|> model.data.additional.AbstractAdditional
  model.data.additional.GeographicShape -up-|> model.data.additional.AbstractAdditional
  model.data.additional.GlobeCoordinate -up-|> model.data.additional.AbstractAdditional
  model.data.additional.LiteralString -up-|> model.data.additional.AbstractAdditional
  model.data.additional.MathematicalExpression -up-|> model.data.additional.AbstractAdditional
  model.data.additional.MonolingualText -up-|> model.data.additional.AbstractAdditional
  model.data.additional.MusicalNotation -up-|> model.data.additional.AbstractAdditional
  model.data.additional.Quantity -up-|> model.data.additional.AbstractAdditional
  model.data.additional.TabularData -up-|> model.data.additional.AbstractAdditional
  model.data.additional.Time -up-|> model.data.additional.AbstractAdditional
  model.data.additional.URL -up-|> model.data.additional.AbstractAdditional
  model.data.pages.Item -up-|> model.data.Datum
  model.data.pages.Item o-- model.data.DatumQueryService : queryService
  model.data.pages.Property -up-|> model.data.Datum
  model.data.pages.Property o-- model.data.DatumQueryService : queryService
  model.data.pages.language.Form o-- model.data.DatumQueryService : queryService
  model.data.pages.language.Lexeme o-- model.data.DatumQueryService : queryService
  model.data.pages.language.Sense o-- model.data.DatumQueryService : queryService
  model.data.source.WebCollector .up.|> model.data.source.Collector
  model.data.source.template.Claim o-- model.data.source.template.Snak : mainsnak
  model.data.source.template.Qualifier o-- model.data.source.template.DataValue : datavalue
  model.data.source.template.Snak o-- model.data.source.template.DataValue : datavalue
  model.prefrences.LayoutProfile o-- ui.cli.LayoutManager : layout
  model.prefrences.LayoutProfileManager .up.|> ui.cli.MenuBarItem
  model.prefrences.LayoutProfileManager o-- model.prefrences.LayoutProfile : current
  model.prefrences.PreferenceManager .up.|> ui.cli.MenuBarItem
  model.prefrences.UserProfile .up.|> ui.cli.MenuBarItem
  model.prefrences.UserProfile o-- model.prefrences.LayoutProfileManager : layout
  model.prefrences.UserProfile o-- model.prefrences.PreferenceManager : preferences
  ui.cli.ItemView o-- ui.cli.ItemViewController : controller
  ui.cli.ItemView o-- model.data.Value : item
  ui.cli.ItemView o-- ui.cli.SearchBar : searchBar
  ui.cli.ItemView o-- ui.cli.StatementList : statements
  ui.cli.ItemViewController o-- ui.cli.LayoutManager : manager
  ui.cli.LayoutManager o-- ui.cli.MenuBar : menuBar
  ui.cli.MenuBar o-- ui.cli.SearchBar : searchBar
  ui.cli.SearchBar .up.|> ui.cli.MenuBarItem
  ui.cli.SearchBar o-- model.data.ScopedSearch : searchService
  ui.cli.StatementList o-- model.data.Value : entity
  ui.cli.StatementList o-- model.data.DatumQueryService : queryService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
